# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title MinMerge
#' @description  Take the minimum of two vectors and merge them
#' @param x a vector
#' @param y a vector
#' @return a vector consisting of the minimum of the two vectors
#' @export
MinMerge <- function(x, y) {
    .Call('_StatComp21085_MinMerge', PACKAGE = 'StatComp21085', x, y)
}

#' @title gcd
#' @description Calculate the greatest common divisor of two numbers
#' @param a an integer
#' @param b an integer
#' @return x the greatest common divisor of two numbers
#' @examples
#' \dontrun{
#' a <- 6
#' b <- 8
#' mygcd(6,8);}
#' @export
gcd <- function(a, b) {
    .Call('_StatComp21085_gcd', PACKAGE = 'StatComp21085', a, b)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param a the fixed parameter greater than 0
#' @param b the fixed parameter greater than 0
#' @param n the integer parameter
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(2000,1,4,50,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, a, b, n, thin) {
    .Call('_StatComp21085_gibbsC', PACKAGE = 'StatComp21085', N, a, b, n, thin)
}

#' @title rbivariate_c 
#' @description Generate a bivariate sampler using Rcpp
#' @param N the number of samples
#' @param n the parameter
#' @param a the parameter
#' @param b the parameter
#' @return a random sample matrix of size N
#' @examples
#' \dontrun{
#' rbivariate_c(1000, 25, 1, 1)
#' }
#' @export
rbivariate_c <- function(N, n, a, b) {
    .Call('_StatComp21085_rbivariate_c', PACKAGE = 'StatComp21085', N, n, a, b)
}

